image: node:10.15.3 # Choose an image matching your project needs

clone:
      depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
      services:
        docker:
          memory: 2048
      caches:
            sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
      steps:
      - step: &build-test-sonarcloud
              name: Build, test and analyze on SonarCloud
              caches:
              - node
              - sonar
              script:
              - npm install
              - npm run lintfile
              - npm run coverage
              - pipe: sonarsource/sonarcloud-scan:1.0.1
                variables:
                  EXTRA_ARGS: '-Dsonar.organization=venturedive -Dsonar.projectKey=<PROJECTKEY> -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.eslint.reportPaths=report.json -Dsonar.tests=src -Dsonar.test.inclusions=**/*.test.js -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.testExecutionReportPaths=test-report.xml'

      - step: &check-quality-gate-sonarcloud
              name: Check the Quality Gate on SonarCloud
              script:
              - pipe: sonarsource/sonarcloud-quality-gate:0.1.3

pipelines:
  branches:
    master:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
